backend:
  name: "git-gateway"
  branch: "main"

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "general"
        file: "_data/settings.json"
        fields:
          - label: "Site Title"
            name: "site_title"
            widget: "string"
          - label: "Site Description"
            name: "site_description"
            widget: "text"
          - label: "Site URL"
            name: "site_url"
            widget: "string"
          - label: "Phone Number"
            name: "phone"
            widget: "string"
          - label: "Email Address"
            name: "email"
            widget: "string"
          - label: "Company Address"
            name: "address"
            widget: "string"
          - label: "Company Description"
            name: "company_description"
            widget: "text"
          - label: "Copyright Text"
            name: "copyright_text"
            widget: "string"
          - label: "Services Section Title"
            name: "services_title"
            widget: "string"
          - label: "Newsletter Title"
            name: "newsletter_title"
            widget: "string"
          - label: "Newsletter Description"
            name: "newsletter_description"
            widget: "text"

  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "_data/home.json"
        fields:
          - label: "Hero Title"
            name: "hero_title"
            widget: "string"
          - label: "Hero Description"
            name: "hero_description"
            widget: "text"
          - label: "Hero Background Image"
            name: "hero_bg_image"
            widget: "image"
            required: false
          - label: "About Section Title"
            name: "about_title"
            widget: "string"
          - label: "About Section Description"
            name: "about_description"
            widget: "text"
          - label: "About Section Image"
            name: "about_image"
            widget: "image"
            required: false
          - label: "Statistics"
            name: "statistics"
            widget: "object"
            fields:
              - label: "Projects Completed"
                name: "projects_completed"
                widget: "string"
              - label: "Projects Label"
                name: "projects_label"
                widget: "string"

  - name: "services"
    label: "Services"
    folder: "_data/services"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Service Name"
        name: "name"
        widget: "string"
      - label: "Service Number"
        name: "number"
        widget: "string"
      - label: "Service Description"
        name: "description"
        widget: "text"
        required: false
      - label: "Service Icon"
        name: "icon"
        widget: "image"
        required: false
      - label: "Featured"
        name: "featured"
        widget: "boolean"
        default: false

  - name: "team"
    label: "Team Members"
    folder: "_data/team"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Position"
        name: "position"
        widget: "string"
      - label: "Bio"
        name: "bio"
        widget: "text"
        required: false
      - label: "Profile Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Social Media"
        name: "social"
        widget: "object"
        fields:
          - label: "LinkedIn"
            name: "linkedin"
            widget: "string"
            required: false
          - label: "Twitter"
            name: "twitter"
            widget: "string"
            required: false
          - label: "Email"
            name: "email"
            widget: "string"
            required: false

  - name: "testimonials"
    label: "Testimonials"
    folder: "_data/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Client Name"
        name: "client_name"
        widget: "string"
      - label: "Client Position"
        name: "client_position"
        widget: "string"
      - label: "Company"
        name: "company"
        widget: "string"
        required: false
      - label: "Testimonial Text"
        name: "testimonial_text"
        widget: "text"
      - label: "Client Photo"
        name: "client_image"
        widget: "image"
        required: false
      - label: "Rating"
        name: "rating"
        widget: "number"
        value_type: "int"
        min: 1
        max: 5
        default: 5

  - name: "blog"
    label: "Blog Posts"
    folder: "_data/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Creative", "Technology", "Business", "Design", "Development"]
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
        required: false
      - label: "Excerpt"
        name: "excerpt"
        widget: "text"
      - label: "Content"
        name: "body"
        widget: "markdown"
      - label: "Author"
        name: "author"
        widget: "string"
        default: "WebNext Team"
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false

  - name: "portfolio"
    label: "Portfolio/Case Studies"
    folder: "_data/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Project Title"
        name: "title"
        widget: "string"
      - label: "Client Name"
        name: "client"
        widget: "string"
      - label: "Project Category"
        name: "category"
        widget: "select"
        options: ["Web Development", "Mobile App", "AI Solutions", "E-commerce", "Custom Software"]
      - label: "Project Description"
        name: "description"
        widget: "text"
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
        required: false
      - label: "Gallery Images"
        name: "gallery"
        widget: "list"
        field: {label: "Image", name: "image", widget: "image"}
        required: false
      - label: "Technologies Used"
        name: "technologies"
        widget: "list"
        required: false
      - label: "Project URL"
        name: "project_url"
        widget: "string"
        required: false
      - label: "Completion Date"
        name: "date"
        widget: "datetime"
      - label: "Featured Project"
        name: "featured"
        widget: "boolean"
        default: false

  - name: "contact_settings"
    label: "Contact Settings"
    files:
      - label: "Contact Information & Form Settings"
        name: "contact"
        file: "_data/contact.json"
        fields:
          - label: "Contact Information"
            name: "contact_info"
            widget: "object"
            fields:
              - label: "Primary Phone"
                name: "phone"
                widget: "string"
                default: "+197-90-56-780"
              - label: "Fax Number"
                name: "fax"
                widget: "string"
                default: "+44-208-1234567"
              - label: "Primary Email"
                name: "email_primary"
                widget: "string"
                default: "info.company@gmail.com"
              - label: "Secondary Email"
                name: "email_secondary"
                widget: "string"
                default: "info.company@yahoo.com"
              - label: "Address Line 1"
                name: "address_line1"
                widget: "string"
                default: "85 Ketch Harbour"
              - label: "Address Line 2"
                name: "address_line2"
                widget: "string"
                default: "RoadBensalem, PA 19020"
              - label: "Google Maps Embed URL"
                name: "map_embed_url"
                widget: "text"
                default: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6678.7619084840835!2d144.9618311901502!3d-37.81450084255415!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad642b4758afc1d%3A0x3119cc820fdfc62e!2sEnvato!5e0!3m2!1sen!2sbd!4v1641984054261!5m2!1sen!2sbd"
          - label: "Contact Form Settings"
            name: "form_settings"
            widget: "object"
            fields:
              - label: "Form Title"
                name: "form_title"
                widget: "string"
                default: "Get in touch!"
              - label: "Form Subtitle"
                name: "form_subtitle"
                widget: "string"
                default: "contact us"
              - label: "Success Message"
                name: "success_message"
                widget: "text"
                default: "Thank you for your message! We'll get back to you soon."
              - label: "Error Message"
                name: "error_message"
                widget: "text"
                default: "Sorry, there was an error sending your message. Please try again."
              - label: "Required Fields"
                name: "required_fields"
                widget: "list"
                default: ["name", "email", "message"]
              - label: "Service Options"
                name: "service_options"
                widget: "list"
                default: ["Web Development", "Mobile App Development", "Digital Marketing", "UI/UX Design", "E-commerce Solutions", "SEO Services", "Consulting", "Support"]
              - label: "Notification Email"
                name: "notification_email"
                widget: "string"
                default: "admin@yourcompany.com"
              - label: "Auto Reply Enabled"
                name: "auto_reply"
                widget: "boolean"
                default: true
              - label: "Spam Protection Enabled"
                name: "spam_protection"
                widget: "boolean"
                default: true
          - label: "Business Hours"
            name: "business_hours"
            widget: "object"
            fields:
              - label: "Monday - Friday"
                name: "monday_friday"
                widget: "string"
                default: "9:00 AM - 6:00 PM"
              - label: "Saturday"
                name: "saturday"
                widget: "string"
                default: "10:00 AM - 4:00 PM"
              - label: "Sunday"
                name: "sunday"
                widget: "string"
                default: "Closed"
              - label: "Timezone"
                name: "timezone"
                widget: "string"
                default: "EST"
          - label: "Social Media Links"
            name: "social_media"
            widget: "object"
            fields:
              - label: "Facebook URL"
                name: "facebook"
                widget: "string"
                default: "https://facebook.com/yourcompany"
              - label: "Twitter URL"
                name: "twitter"
                widget: "string"
                default: "https://twitter.com/yourcompany"
              - label: "LinkedIn URL"
                name: "linkedin"
                widget: "string"
                default: "https://linkedin.com/company/yourcompany"
              - label: "Instagram URL"
                name: "instagram"
                widget: "string"
                default: "https://instagram.com/yourcompany"

  - name: "contact_submissions"
    label: "Contact Form Submissions"
    folder: "_data/submissions"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Email"
        name: "email"
        widget: "string"
      - label: "Service"
        name: "service"
        widget: "string"
      - label: "Message"
        name: "message"
        widget: "text"
      - label: "Submission Date"
        name: "date"
        widget: "datetime"
      - label: "IP Address"
        name: "ip"
        widget: "string"
      - label: "Status"
        name: "status"
        widget: "select"
        options: ["New", "Read", "Replied", "Archived"]