# Local development configuration for Netlify CMS
# This config works without Git Gateway for local testing

local_backend: true

backend:
  name: "test-repo"

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "general"
        file: "_data/settings.json"
        fields:
          - label: "Site Title"
            name: "site_title"
            widget: "string"
          - label: "Site Description"
            name: "site_description"
            widget: "text"
          - label: "Site URL"
            name: "site_url"
            widget: "string"
          - label: "Phone Number"
            name: "phone"
            widget: "string"
          - label: "Email Address"
            name: "email"
            widget: "string"
          - label: "Company Address"
            name: "address"
            widget: "string"
          - label: "Company Description"
            name: "company_description"
            widget: "text"
          - label: "Copyright Text"
            name: "copyright_text"
            widget: "string"
          - label: "Services Section Title"
            name: "services_title"
            widget: "string"
          - label: "Newsletter Title"
            name: "newsletter_title"
            widget: "string"
          - label: "Newsletter Description"
            name: "newsletter_description"
            widget: "text"

  - name: "contact_settings"
    label: "Contact Settings"
    files:
      - label: "Contact Information & Form Settings"
        name: "contact"
        file: "_data/contact.json"
        fields:
          - label: "Contact Information"
            name: "contact_info"
            widget: "object"
            fields:
              - label: "Primary Phone"
                name: "phone"
                widget: "string"
                default: "+197-90-56-780"
              - label: "Primary Email"
                name: "email_primary"
                widget: "string"
                default: "info.company@gmail.com"
              - label: "Address Line 1"
                name: "address_line1"
                widget: "string"
                default: "85 Ketch Harbour"
              - label: "Address Line 2"
                name: "address_line2"
                widget: "string"
                default: "RoadBensalem, PA 19020"
          - label: "Contact Form Settings"
            name: "form_settings"
            widget: "object"
            fields:
              - label: "Form Title"
                name: "form_title"
                widget: "string"
                default: "Get in touch!"
              - label: "Success Message"
                name: "success_message"
                widget: "text"
                default: "Thank you for your message! We'll get back to you soon."
              - label: "Error Message"
                name: "error_message"
                widget: "text"
                default: "Sorry, there was an error sending your message. Please try again."
              - label: "Service Options"
                name: "service_options"
                widget: "list"
                default: ["Web Development", "Mobile App Development", "Digital Marketing", "UI/UX Design"]