backend:
  name: "git-gateway"
  branch: "main"

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"