backend:
  name: "git-gateway"
  branch: "main"

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "_data/settings.json"
        fields:
          - label: "Site Title"
            name: "site_title"
            widget: "string"
            default: "WebNext - Web & AI Solutions"
          - label: "Site Description"
            name: "site_description"
            widget: "text"
            default: "Innovative web development, mobile apps, and AI-powered solutions"
          - label: "Phone Number"
            name: "phone"
            widget: "string"
            default: "+60 11-6195 3584"
          - label: "Email Address"
            name: "email"
            widget: "string"
            default: "hello@webnext.pro"
          - label: "Hero Title"
            name: "hero_title"
            widget: "string"
            default: "Web & AI Solutions"
          - label: "Hero Description"
            name: "hero_description"
            widget: "text"
            default: "Innovative web development, mobile apps, and AI-powered solutions to transform your business operations."
          - label: "About Section Title"
            name: "about_title"
            widget: "string"
            default: "We Build Innovative Web & AI Solutions"
          - label: "About Section Description"
            name: "about_description"
            widget: "text"
            default: "We specialize in cutting-edge web development, mobile applications, and AI-powered solutions that drive business growth and operational efficiency."
          - label: "Company Address"
            name: "address"
            widget: "string"
            default: "Remote Services Worldwide"