backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "assets/img/uploads" # Media files will be stored in the repo under assets/img/uploads
public_folder: "/assets/img/uploads" # The src attribute for uploaded media will begin with /assets/img/uploads

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - label: "Phone Number (Header)"
            name: "header_phone"
            widget: "string"
            default: "+60 11-6195 3584"
            hint: "Phone number displayed in the header"
          - label: "Hero Title"
            name: "hero_title"
            widget: "text"
            default: "Web & AI Solutions"
            hint: "Main heading in the hero section"
          - label: "Hero Description"
            name: "hero_description"
            widget: "text"
            default: "Innovative web development, mobile apps, and AI-powered solutions to transform your business operations."
            hint: "Description text in the hero section"
          - label: "About Section Title"
            name: "about_title"
            widget: "string"
            default: "We Build Innovative Web & AI Solutions"
            hint: "Title in the about section"
          - label: "About Section Description"
            name: "about_description"
            widget: "text"
            default: "We specialize in cutting-edge web development, mobile applications, and AI-powered solutions that drive business growth and operational efficiency."
            hint: "Description in the about section"
          - label: "Services Title"
            name: "services_title"
            widget: "string"
            default: "our main services"
            hint: "Title for the services section"
          - label: "Company Description (Footer)"
            name: "company_description"
            widget: "text"
            default: "WebNext delivers innovative web development, mobile applications, and AI-powered solutions to transform your business operations and drive growth."
            hint: "Company description in the footer"
          - label: "Company Address"
            name: "company_address"
            widget: "string"
            default: "Remote Services Worldwide"
            hint: "Company address in the footer"
          - label: "Company Email"
            name: "company_email"
            widget: "string"
            default: "hello@webnext.pro"
            hint: "Company email address"
          - label: "Company Phone"
            name: "company_phone"
            widget: "string"
            default: "+60 11-6195 3584"
            hint: "Company phone number in the footer"
          - label: "Copyright Text"
            name: "copyright_text"
            widget: "string"
            default: "All Copyright 2024 by WebNext"
            hint: "Copyright text in the footer"
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - label: "Service Name"
                name: "name"
                widget: "string"
              - label: "Service Number"
                name: "number"
                widget: "string"
            default:
              - name: "Web Development"
                number: "01"
              - name: "App Development"
                number: "02"
              - name: "AI Solutions"
                number: "03"
              - name: "AI Automation"
                number: "04"
              - name: "AI Customer Support"
                number: "05"
              - name: "Cloud Platforms"
                number: "06"
              - name: "Static Websites"
                number: "01"
              - name: "Dynamic Websites"
                number: "02"
              - name: "iOS Apps"
                number: "03"
              - name: "Custom Solutions"
                number: "04"
              - name: "Mobile app"
                number: "05"
              - name: "Creative Design"
                number: "06"
          - label: "Team Members"
            name: "team_members"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Position"
                name: "position"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
                required: false
            default:
              - name: "Leslie Alexander"
                position: "Programmer"
                image: "assets/img/team/rd1.png"
              - name: "Darlene Robertson"
                position: "UI/UX designer"
                image: "assets/img/team/rd2.png"
              - name: "Marvin McKinney"
                position: "Web developer"
                image: "assets/img/team/rd3.png"
              - name: "Ronald Richards"
                position: "Team Leader"
                image: "assets/img/team/rd4.png"
          - label: "Statistics"
            name: "statistics"
            widget: "object"
            fields:
              - label: "Projects Completed"
                name: "projects_completed"
                widget: "string"
                default: "25K+"
              - label: "Projects Label"
                name: "projects_label"
                widget: "string"
                default: "Completed projects"
          - label: "Awards"
            name: "awards"
            widget: "list"
            fields:
              - label: "Year"
                name: "year"
                widget: "string"
              - label: "Award Name"
                name: "award_name"
                widget: "string"
              - label: "Award Description"
                name: "award_description"
                widget: "string"
            default:
              - year: "2019"
                award_name: "Awwwards"
                award_description: "Website of the day"
              - year: "2021"
                award_name: "Awwwards"
                award_description: "National design contest"
              - year: "2023"
                award_name: "Awwwards"
                award_description: "Apps of the day"
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - label: "Client Name"
                name: "client_name"
                widget: "string"
              - label: "Client Position"
                name: "client_position"
                widget: "string"
              - label: "Testimonial Text"
                name: "testimonial_text"
                widget: "text"
              - label: "Client Image"
                name: "client_image"
                widget: "image"
                required: false
            default:
              - client_name: "Daniel Smith"
                client_position: "Senior engineer"
                testimonial_text: "Posuere luctus orci. Donec vitae mattis quam, vitae tempor arcu. Aenean non odio porttitor, convallis erat sit amet, facilisis velit. Nulla ornare convallis malesuada. Phasellus molestie, ipsum ac fringilla."
                client_image: "assets/img/testimonial/t-version01.png"
          - label: "Blog Posts"
            name: "blog_posts"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Category"
                name: "category"
                widget: "string"
              - label: "Date"
                name: "date"
                widget: "string"
              - label: "Featured Image"
                name: "featured_image"
                widget: "image"
                required: false
            default:
              - title: "non sit libero viverrid mollies Non ligula incident cangue porta attention simply"
                category: "Creative"
                date: "MARCH 24, 2024"
                featured_image: "assets/img/blog/blogv3-big.png"
              - title: "Pellentesque dignissim malesuada varius et semper semper rutrum ad risus felis eros."
                category: "Creative"
                date: "MARCH 24, 2024"
                 featured_image: "assets/img/blog/blog-hover2.png"
          - label: "Navigation Menu"
            name: "navigation"
            widget: "list"
            fields:
              - label: "Menu Item Name"
                name: "name"
                widget: "string"
              - label: "Menu Link"
                name: "link"
                widget: "string"
              - label: "Has Submenu"
                name: "has_submenu"
                widget: "boolean"
                default: false
              - label: "Submenu Items"
                name: "submenu"
                widget: "list"
                required: false
                fields:
                  - label: "Submenu Item Name"
                    name: "name"
                    widget: "string"
                  - label: "Submenu Link"
                    name: "link"
                    widget: "string"
            default:
              - name: "Home"
                link: "index.html"
                has_submenu: true
                submenu:
                  - name: "Home Version-1"
                    link: "index.html"
                  - name: "Home Version-2"
                    link: "index2.html"
              - name: "About Us"
                link: "about.html"
                has_submenu: false
              - name: "Services"
                link: "service.html"
                has_submenu: true
                submenu:
                  - name: "Service"
                    link: "service.html"
                  - name: "Service Details"
                    link: "service-details.html"
              - name: "Pages"
                link: "#"
                has_submenu: true
                submenu:
                  - name: "About"
                    link: "about.html"
                  - name: "Pricing Plan"
                    link: "pricing.html"
                  - name: "Case Study"
                    link: "study-grid.html"
                  - name: "Case Study Details"
                    link: "study-details.html"
                  - name: "Team Grid"
                    link: "team.html"
                  - name: "Team Details"
                    link: "team-details.html"
                  - name: "Faqs"
                    link: "faq.html"
                  - name: "Contact"
                    link: "contact.html"
                  - name: "Oops 404"
                    link: "oops.html"
              - name: "Blog"
                link: "#"
                has_submenu: true
                submenu:
                  - name: "Blog Grid"
                    link: "blog-grid.html"
                  - name: "Blog List"
                    link: "blog-list.html"
                  - name: "Blog Details"
                    link: "blog-details.html"
              - name: "Contact Us"
                 link: "contact.html"
                 has_submenu: false
          - label: "Footer Menu"
            name: "footer_menu"
            widget: "object"
            fields:
              - label: "Quick Links"
                name: "quick_links"
                widget: "list"
                fields:
                  - label: "Link Name"
                    name: "name"
                    widget: "string"
                  - label: "Link URL"
                    name: "url"
                    widget: "string"
                default:
                  - name: "About WebNext"
                    url: "about.html"
                  - name: "Our Services"
                    url: "service.html"
                  - name: "Our Blogs"
                    url: "blog-grid.html"
                  - name: "Contact Us"
                    url: "contact.html"
              - label: "Services Links"
                name: "services_links"
                widget: "list"
                fields:
                  - label: "Service Name"
                    name: "name"
                    widget: "string"
                  - label: "Service URL"
                    name: "url"
                    widget: "string"
                default:
                  - name: "Web Development"
                    url: "service.html"
                  - name: "App Development"
                    url: "study-grid.html"
                  - name: "AI Solutions"
                    url: "study-grid.html"
                  - name: "Cloud Platforms"
                    url: "service.html"
              - label: "Newsletter Title"
                name: "newsletter_title"
                widget: "string"
                default: "Newsletter"
              - label: "Newsletter Description"
                name: "newsletter_description"
                widget: "text"
                default: "Sign up to seargin weekly newsletter to get the latest updates."
          - label: "Social Media Links"
            name: "social_media"
            widget: "list"
            fields:
              - label: "Platform Name"
                name: "platform"
                widget: "string"
              - label: "URL"
                name: "url"
                widget: "string"
              - label: "Icon Class"
                name: "icon"
                widget: "string"
                hint: "CSS class or SVG code for the social media icon"
            default:
              - platform: "Facebook"
                url: "#"
                icon: "fab fa-facebook-f"
              - platform: "Twitter"
                url: "#"
                icon: "fab fa-twitter"
              - platform: "LinkedIn"
                url: "#"
                icon: "fab fa-linkedin-in"
              - platform: "YouTube"
                url: "#"
                icon: "fab fa-youtube"

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "general"
        file: "_data/settings.json"
        fields:
          - label: "Site Title"
            name: "site_title"
            widget: "string"
            default: "WebNext - Web & AI Solutions"
          - label: "Site Description"
            name: "site_description"
            widget: "text"
            default: "Innovative web development, mobile apps, and AI-powered solutions"
          - label: "Site URL"
            name: "site_url"
            widget: "string"
            default: "https://webnext.pro"